#!/bin/zsh
# Render every bench tile, check it, and tile them into A4 contact sheets.
#
#   ./sheet.sh                 everything
#   ./sheet.sh S2-T07          just that tile, re-rendered in place
#   ./sheet.sh --models tee    every tile of one model
#
# Each tile carries its own id. A tile id is stable as long as expect.txt keeps
# its order, so "S2-T07's corner is broken" names one render, one model and one
# set of arguments, and sheets/INDEX.md resolves it without opening an image.
#
# Every row is checkpointed to INDEX.md as it completes: a run killed by the
# stall watchdog leaves everything it finished.
set -u
cd "${0:A:h}"

BIN=${BIN:-../build/OpenSCAD.app/Contents/MacOS/OpenSCAD}
FLAGS=${FLAGS:---enable=fillet}   # the modules are experimental; without this every model is an unknown-module error
TILE_W=${TILE_W:-700}
TILE_H=${TILE_H:-560}
COLS=3
ROWS=4
PER_SHEET=$((COLS * ROWS))
FONT=/System/Library/Fonts/Helvetica.ttc

[[ -x $BIN ]] || { print -u2 "no binary at $BIN -- set BIN="; exit 1; }
# Trap: make reports "Built target" for binaries that do not exist, and builds
# are silently discarded here. Say what was measured, always.
print "binary: $BIN"
print "        built $(stat -f '%Sm' "$BIN")"
print "sources newer than the binary:"
find ../src -name '*.cc' -newer "$BIN" -o -name '*.h' -newer "$BIN" | head -5
print ""

mkdir -p tiles sheets
INDEX=sheets/INDEX.md
ONLY=""
MODEL_FILTER=""
if [[ ${1:-} == --models ]]; then MODEL_FILTER=${2:-}; elif [[ -n ${1:-} ]]; then ONLY=$1; fi

# Build the tile list from expect.txt: every model renders at stock defaults,
# and every model carrying curvature renders again with $fn forced to the
# fragment count it actually achieves. Those two tiles side by side are A2
# check 1 made visible -- if they differ, the classifier is reading $fn.
tiles=()
while read -r name fn rest; do
  [[ -z $name || $name == \#* ]] && continue
  [[ -n $MODEL_FILTER && $name != *$MODEL_FILTER* ]] && continue
  tiles+=("$name|defaults|")
  [[ $fn == - || $fn == skip ]] || tiles+=("$name|fn=$fn|-D FNSET=$fn")
done < expect.txt

total=${#tiles[@]}
print "$total tiles, $(( (total + PER_SHEET - 1) / PER_SHEET )) sheets\n"

if [[ -z $ONLY && -z $MODEL_FILTER ]]; then
  print "# Bench contact sheets\n" > $INDEX
  print "Generated by \`sheet.sh\`. Tile ids are stable while expect.txt keeps its order.\n" >> $INDEX
  print "| tile | model | args | mesh | warnings |" >> $INDEX
  print "|---|---|---|---|---|" >> $INDEX
fi

i=0
for entry in $tiles; do
  i=$((i + 1))
  sheet=$(( (i - 1) / PER_SHEET + 1 ))
  slot=$(( (i - 1) % PER_SHEET + 1 ))
  id=$(printf "S%d-T%02d" $sheet $slot)
  [[ -n $ONLY && $ONLY != $id ]] && continue

  name=${entry%%|*}; rest=${entry#*|}
  label=${rest%%|*}; args=${rest#*|}

  png=tiles/$id.png
  off=tiles/$id.off
  log=tiles/$id.log

  # Render the solid and the mesh from the same invocation set, so the picture
  # and the numbers are always about the same build.
  ${=BIN} $=FLAGS --backend=manifold --render --viewall --autocenter \
      --imgsize=$TILE_W,$TILE_H --projection=p --colorscheme=Cornfield \
      $=args -o $png models/$name.scad > $log 2>&1
  ${=BIN} $=FLAGS --backend=manifold --render $=args -o $off models/$name.scad >> $log 2>&1

  if [[ -f $off ]]; then
    stat=$(python3 mesh.py $off 2>&1 | sed "s|$off: ||")
  else
    stat="NO OUTPUT"
  fi
  warn=$(grep -c "WARNING:" $log 2>/dev/null); warn=${warn:-0}
  short=$(print "$stat" | cut -d' ' -f1)

  # Caption every tile with what it is and whether it is valid, so a sheet read
  # on its own never needs the index to say "this one is broken".
  if [[ -f $png ]]; then
    magick $png -background white -bordercolor white -border 6 \
      -font $FONT -pointsize 22 -fill black \
      label:"$id  $name  ($label)" -gravity center -append \
      -font $FONT -pointsize 18 -fill $([[ $short == VALID ]] && print gray30 || print red) \
      label:"$short  warnings=$warn" -gravity center -append \
      tiles/$id-labeled.png 2>/dev/null
  fi

  print "$id $name $label -> $short warnings=$warn"
  if [[ -z $ONLY && -z $MODEL_FILTER ]]; then
    print "| $id | $name | ${args:-(defaults)} | $stat | $warn |" >> $INDEX
  fi
done

# Montage. Sheets are rebuilt from whatever labelled tiles exist, so a single
# re-rendered tile lands in its sheet without re-rendering the other eleven.
nsheets=$(( (total + PER_SHEET - 1) / PER_SHEET ))
for s in $(seq 1 $nsheets); do
  files=(tiles/S$s-T*-labeled.png(N))
  (( ${#files} )) || continue
  montage -background white -tile ${COLS}x${ROWS} -geometry +10+10 \
      $files sheets/sheet-$s.png 2>/dev/null
  magick sheets/sheet-$s.png -background white -font $FONT -pointsize 34 -fill black \
      label:"fillet bench -- sheet $s of $nsheets" -gravity center +swap -append \
      sheets/sheet-$s.png 2>/dev/null
  print "sheets/sheet-$s.png"
done
